name: Update README
on: workflow_dispatch
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update README
        env:
          CURRENT_VERSION: 1.1.0-alpha-11
        run: |
          ./.github/scripts/update_readme.sh ${CURRENT_VERSION}
          git add README.md
          git commit -m "docs: update latest version number"
          git fetch origin
          git merge origin master
          git push origin master
